# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [1]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np
import datetime

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [3]:
data_url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data'

In [4]:
data = pd.read_table(data_url, sep = "\s+") 
data.head()

/Users/wontaek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

In [5]:
data = pd.read_table(data_url, sep = "\s+", parse_dates = [[0,1,2]]) 
data.head()

/Users/wontaek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [6]:
data['Yr_Mo_Dy'].unique()

array(['2061-01-01T00:00:00.000000000', '2061-01-02T00:00:00.000000000',
       '2061-01-03T00:00:00.000000000', ...,
       '1978-12-29T00:00:00.000000000', '1978-12-30T00:00:00.000000000',
       '1978-12-31T00:00:00.000000000'], dtype='datetime64[ns]')

In [7]:
datetime.date(2019, 3, 10)

datetime.date(2019, 3, 10)

In [8]:
# 삼항연산자를 사용하여 연산 처리

def convert_date(x):
    year = x.year - 100 if x.year > 1989 else x.year
    date_log = datetime.date(year, x.month, x.day)
    
    return date_log

# convert datetime 
data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].apply(convert_date)
data.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [9]:
data['Yr_Mo_Dy'].dtype

dtype('O')

In [10]:
# conver columns type
# pd.to_datetime을 사용하면 datetime 형식으로 바꿀 수 있다.

data['Yr_Mo_Dy'] = pd.to_datetime(data['Yr_Mo_Dy'])

In [11]:
data['Yr_Mo_Dy'].dtype

dtype('<M8[ns]')

In [13]:
# 이렇게도 바꿀 수 있다. 사실 이게 더 편하다.(알기만 하면...)

data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].astype('datetime64[ns]')

In [14]:
data['Yr_Mo_Dy'].dtype

dtype('<M8[ns]')

In [15]:
data = data.set_index('Yr_Mo_Dy')

In [16]:
data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [17]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [18]:
data.notnull().sum()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

### flatten

- ndarray.flatten(order='C')¶
  - Return a copy of the array collapsed into one dimension.
  - reference : https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html

In [19]:
data.fillna(0).values

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71,  0.  , 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [14.  , 10.29, 14.42, ..., 16.42, 18.88, 29.58],
       [18.5 , 14.04, 21.29, ..., 12.12, 14.67, 28.79],
       [20.33, 17.41, 27.29, ..., 11.38, 12.08, 22.08]])

In [20]:
data.fillna(0).values.flatten()

array([15.04, 14.96, 13.17, ..., 11.38, 12.08, 22.08])

In [21]:
data.fillna(0).values.flatten().mean()

10.223864592840483

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [22]:
data.describe()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
75%,15.920000,14.040000,14.670000,8.420000,13.540000,9.670000,12.960000,11.420000,11.190000,11.630000,16.880000,19.830000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

In [23]:
data.describe(percentiles=[])

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

In [24]:
data.describe(percentiles=[0.25, 0.5])

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [25]:
day_stats = pd.DataFrame()

In [26]:
day_stats # empty dataframe

Empty DataFrame
Columns: []
Index: []

In [28]:
data.min(axis = 1)[0:10]

Yr_Mo_Dy
1961-01-01    9.29
1961-01-02    6.50
1961-01-03    6.17
1961-01-04    1.79
1961-01-05    6.17
1961-01-06    4.42
1961-01-07    4.96
1961-01-08    5.91
1961-01-09    4.75
1961-01-10    6.54
dtype: float64

In [29]:
# 결과를 보니 행렬을 기준으로 각 열의 가장 작은 값을 가져와서 만드는 방법

day_stats['min'] = data.min(axis = 1)

In [30]:
day_stats.head()

             min
Yr_Mo_Dy
1961-01-01  9.29
1961-01-02  6.50
1961-01-03  6.17
1961-01-04  1.79
1961-01-05  6.17

In [31]:
day_stats['max'] = data.max(axis = 1)

In [32]:
day_stats.head()

             min    max
Yr_Mo_Dy
1961-01-01  9.29  18.50
1961-01-02  6.50  17.54
1961-01-03  6.17  18.50
1961-01-04  1.79  11.75
1961-01-05  6.17  13.33

In [43]:
day_stats['mean'] = data.mean(axis = 1) # mean
day_stats['std'] = data.std(axis = 1) # standard deviations

In [44]:
day_stats.head()

             min    max       mean       std
Yr_Mo_Dy
1961-01-01  9.29  18.50  13.018182  2.808875
1961-01-02  6.50  17.54  11.336364  3.188994
1961-01-03  6.17  18.50  11.641818  3.681912
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [45]:
data.loc[(data.index.month == 1) & (data.index.year == 1961) | (data.index.year == 1962)].mean()

RPT    12.444467
VAL    10.253063
ROS    11.865707
KIL     7.021367
SHA    10.688452
BIR     7.486616
DUB    11.033561
CLA     8.828051
MUL     8.377020
CLO     9.710000
BEL    13.005076
MAL    14.353722
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

### to_period, date_range 학습하기
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.to_period.html

In [46]:
>>> df = pd.DataFrame({"y": [1,2,3]},
...                   index=pd.to_datetime(["2000-03-31 00:00:00",
...                                         "2000-05-31 00:00:00",
...                                         "2000-08-31 00:00:00"]))
>>> df.index.to_period("M")

PeriodIndex(['2000-03', '2000-05', '2000-08'], dtype='period[M]', freq='M')

In [47]:
df

            y
2000-03-31  1
2000-05-31  2
2000-08-31  3

In [48]:
>>> idx = pd.date_range("2017-01-01", periods=2)
>>> idx.to_period()

PeriodIndex(['2017-01-01', '2017-01-02'], dtype='period[D]', freq='D')

In [49]:
data.index.to_period('A')

PeriodIndex(['1961', '1961', '1961', '1961', '1961', '1961', '1961', '1961',
             '1961', '1961',
             ...
             '1978', '1978', '1978', '1978', '1978', '1978', '1978', '1978',
             '1978', '1978'],
            dtype='period[A-DEC]', name='Yr_Mo_Dy', length=6574, freq='A-DEC')

In [51]:
data.groupby(data.index.to_period('A')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [52]:
data.groupby(data.index.to_period("M")).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
1961-06,9.904138,8.520333,8.867000,6.083000,10.824000,6.707333,9.095667,8.849333,9.086667,9.940333,13.995000,14.553793
1961-07,10.614194,8.221613,9.110323,6.340968,10.532581,6.198387,8.353333,8.284194,8.077097,8.891613,11.092581,12.312903
1961-08,12.035000,10.133871,10.335806,6.845806,12.715161,8.441935,10.093871,10.460968,9.111613,10.544667,14.410000,14.345333
1961-09,12.531000,9.656897,10.776897,7.155517,11.003333,7.234000,8.206000,8.936552,7.728333,9.931333,13.718333,12.921667
1961-10,14.289667,10.915806,12.236452,8.154839,11.865484,8.333871,11.194194,9.271935,8.942667,11.455806,14.229355,16.793226
1961-11,10.896333,8.592667,11.850333,6.045667,9.123667,6.250667,10.869655,6.313667,6.575000,8.383667,10.776667,12.146000
1961-12,14.973548,11.903871,13.980323,7.073871,11.323548,8.302258,11.753548,8.163226,7.965806,9.246774,12.239355,13.098710
1962-01,14.783871,13.160323,12.591935,7.538065,11.779677,8.720000,14.211935,9.600000,9.670000,11.498710,16.369355,15.661613
1962-02,15.844643,12.041429,15.178929,9.262963,13.821429,9.726786,16.916429,11.285357,12.021071,12.126429,16.705357,18.426786
1962-03,11.634333,8.602258,12.110645,6.403226,10.352258,6.732258,10.223226,7.641935,7.092258,8.052581,9.690000,11.509000
1962-04,12.160667,9.676667,12.088333,7.163000,10.544000,7.558000,11.480000,8.722000,8.703667,9.311667,12.234333,11.780667
1962-05,12.745806,10.865484,11.874839,7.471935,11.285806,7.209032,10.105806,9.084516,7.868065,9.293226,12.130000,12.922581
1962-06,10.305667,9.677000,9.996333,6.846667,10.711333,7.441333,10.548667,10.306667,9.196000,10.520333,13.757000,15.218333
1962-07,9.981935,8.370645,9.753548,6.093226,9.112903,5.877097,7.781613,8.123226,6.829677,8.613226,10.783871,11.326129
1962-08,10.964194,9.694194,10.184516,6.701290,10.465161,7.009032,11.136774,9.097419,8.645484,9.511613,13.119032,15.420968
1962-09,11.176333,9.507000,11.640000,6.164333,9.722333,6.214000,8.488000,7.020333,6.372667,8.286000,11.483667,12.313333
1962-10,9.699355,8.063548,9.357097,4.818065,8.432258,5.730000,8.448065,7.626774,6.630645,9.091290,13.286774,14.090323
1962-11,11.071333,7.984000,12.035667,5.740000,8.135667,6.338333,9.615333,5.943000,6.362333,8.084333,9.786667,13.298333
1962-12,16.785484,13.753548,14.276452,9.557419,13.724839,10.321613,13.735806,11.212258,10.683548,11.881935,16.043548,20.074516
1963-01,14.868387,11.112903,15.121613,6.635806,11.080645,7.835484,12.797419,9.844839,7.841613,9.390000,11.428710,18.822258
1963-02,14.418929,11.876429,15.697500,8.611786,12.887857,9.600357,12.729286,10.823214,8.981786,10.355714,13.266429,17.120714
1963-03,14.853871,12.271290,14.295806,9.268387,13.112903,10.088065,12.168387,11.340968,9.690968,11.515484,13.982903,14.132581
1963-04,11.616000,10.138000,13.233667,7.990333,11.515333,9.727000,11.979000,11.353000,10.341667,11.900333,13.875667,16.333667
1963-05,12.879677,11.010645,12.881290,8.411613,12.981613,9.739677,12.280968,10.964194,10.745161,11.394839,14.777097,14.975161
1963-06,10.623333,8.434667,11.685000,6.420333,10.142667,7.219333,9.267333,9.589333,8.583667,9.585333,12.098000,11.358667
...,...,...,...,...,...,...,...,...,...,...,...,...
1976-07,9.687742,7.980968,8.267742,4.631613,7.576774,4.927419,6.994839,5.135806,7.941290,6.491290,10.264194,11.912258
1976-08,7.640645,5.366129,9.000645,3.142258,4.695484,3.847742,5.437097,3.362581,5.946452,4.496452,7.079677,9.438387
1976-09,11.703667,10.515333,10.466333,5.313333,8.761333,7.062333,8.617667,6.415333,8.953333,7.263333,11.587000,17.634000
1976-10,12.427097,9.572258,10.640000,4.885484,9.393548,6.906452,6.380323,6.933226,7.552258,7.449032,11.837742,15.078065
1976-11,10.962667,9.443667,9.202000,3.696000,7.459333,7.026333,9.058333,5.791000,6.577000,7.512333,12.568333,15.685333
1976-12,11.962258,10.086774,10.474516,3.383871,7.645484,6.148387,8.034516,4.500000,5.952258,6.147742,7.814839,14.346774
1977-01,13.404516,10.377742,12.764839,5.884516,9.159677,8.005161,10.107419,7.211613,8.280000,9.328387,12.131935,18.830000
1977-02,12.336786,11.898929,12.016786,5.317500,10.134643,9.423929,10.949643,7.965357,9.320000,8.711429,11.435357,17.561429
1977-03,16.750000,14.499677,16.118387,8.414516,13.293871,11.562258,14.283226,11.361613,12.102581,11.906452,15.863226,19.133548
1977-04,14.955333,12.293000,12.689667,7.422333,11.740000,10.137000,13.887667,9.574000,10.342333,11.419667,15.593667,18.274667
1977-05,9.441290,7.173871,12.455806,4.507742,6.198387,6.689677,9.226452,5.638387,6.699355,6.045484,10.213548,11.936129
1977-06,11.040000,8.353000,12.228000,4.864000,8.790333,7.209667,8.799667,5.931000,7.065333,6.583333,11.321333,11.175333
1977-07,10.881935,8.663548,10.816452,5.419677,9.014839,7.600000,9.961935,6.526129,7.980968,7.620000,12.924194,12.186774
1977-08,9.233548,7.727742,10.679032,4.453871,6.620645,5.961290,8.943548,4.543226,6.384839,5.694839,9.825161,11.659355
1977-09,12.472333,10.742667,11.849333,5.638667,10.077333,8.242667,11.939333,7.923000,8.828000,8.506333,14.051000,17.030333
1977-10,15.004516,13.960000,12.819677,6.754194,11.779032,9.671613,12.924839,11.875161,11.481290,10.340323,17.640968,19.842903
1977-11,16.946667,15.444667,13.561333,7.584000,12.088667,9.161333,14.051000,11.286000,10.318667,10.327000,17.215333,22.333000
1977-12,14.751935,12.744839,13.469677,6.592258,11.247742,9.466774,13.231613,10.703871,10.401613,9.415484,13.237419,19.299677
1978-01,14.291935,11.872258,12.014194,6.463226,11.402903,7.517097,12.207097,10.206452,9.549032,9.247419,15.101613,20.715806
1978-02,14.143571,12.153214,13.803214,6.828929,11.196786,7.858929,11.903214,11.068929,10.052143,8.093929,10.353929,17.298571
1978-03,14.717097,14.601935,13.334194,8.231290,12.783226,9.488710,12.129355,11.665161,11.656452,9.657097,14.234194,18.611290
1978-04,11.805000,11.255667,12.516333,5.920333,10.218000,7.301667,8.586333,8.306667,8.537000,6.999000,11.190667,14.152000
1978-05,8.270645,7.226774,6.901613,3.740645,6.973871,4.449677,5.420968,6.130645,5.742581,5.926452,9.263548,10.756452
1978-06,11.386667,9.474333,10.253333,6.053000,10.395333,7.490333,7.928000,7.802000,8.220333,7.550000,11.501000,15.078667
1978-07,12.820000,9.750968,9.910323,6.483871,10.055161,7.820645,7.831935,8.459355,8.523871,7.732903,12.648710,14.077419
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [53]:
data.index.to_period('W')

PeriodIndex(['1960-12-26/1961-01-01', '1961-01-02/1961-01-08',
             '1961-01-02/1961-01-08', '1961-01-02/1961-01-08',
             '1961-01-02/1961-01-08', '1961-01-02/1961-01-08',
             '1961-01-02/1961-01-08', '1961-01-02/1961-01-08',
             '1961-01-09/1961-01-15', '1961-01-09/1961-01-15',
             ...
             '1978-12-18/1978-12-24', '1978-12-18/1978-12-24',
             '1978-12-18/1978-12-24', '1978-12-25/1978-12-31',
             '1978-12-25/1978-12-31', '1978-12-25/1978-12-31',
             '1978-12-25/1978-12-31', '1978-12-25/1978-12-31',
             '1978-12-25/1978-12-31', '1978-12-25/1978-12-31'],
            dtype='period[W-SUN]', name='Yr_Mo_Dy', length=6574, freq='W-SUN')

In [54]:
data.groupby(data.index.to_period('W')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1960-12-26/1961-01-01,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-02/1961-01-08,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-09/1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-16/1961-01-22,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-23/1961-01-29,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
1961-01-30/1961-02-05,16.827143,15.460000,12.618571,8.247143,13.361429,9.107143,12.204286,8.548571,9.821429,9.460000,14.012857,11.935714
1961-02-06/1961-02-12,19.684286,16.417143,17.304286,10.774286,14.718571,12.522857,14.934286,14.850000,14.064286,14.440000,21.832857,19.155714
1961-02-13/1961-02-19,15.130000,15.091429,13.797143,10.083333,13.410000,11.868571,9.542857,12.128571,12.375714,13.542857,21.167143,16.584286
1961-02-20/1961-02-26,15.221429,13.625714,14.334286,8.524286,13.655714,10.114286,11.150000,10.875714,10.392857,12.730000,16.304286,14.322857
1961-02-27/1961-03-05,12.101429,12.951429,11.063333,7.834286,12.101429,9.238571,10.232857,11.130000,10.383333,12.370000,17.842857,13.951667
1961-03-06/1961-03-12,9.376667,11.578571,10.845714,7.137143,10.940000,9.488571,6.881429,9.637143,9.885714,10.458571,16.701429,14.420000
1961-03-13/1961-03-19,11.911429,13.501429,11.607143,7.084286,10.751429,8.652857,10.041429,10.220000,10.101429,11.627143,19.350000,16.227143
1961-03-20/1961-03-26,9.567143,8.387143,9.695714,6.648571,8.964286,7.982857,10.774286,8.977143,10.904286,11.481429,14.037143,18.134286
1961-03-27/1961-04-02,10.757143,8.852857,9.501429,7.300000,9.975714,9.165714,11.125714,9.061429,10.478333,9.631429,13.471429,13.900000
1961-04-03/1961-04-09,11.964286,10.654286,13.607143,5.958571,9.494286,7.637143,7.107143,8.041429,8.161429,7.238571,11.712857,11.371429
1961-04-10/1961-04-16,8.965714,8.000000,8.787143,4.971429,6.405714,4.947143,5.005714,4.994286,5.718571,6.178571,9.482857,8.690000
1961-04-17/1961-04-23,12.621429,10.438571,10.255714,7.768571,10.357143,7.798571,9.000000,9.111429,8.767143,9.551429,13.620000,12.470000
1961-04-24/1961-04-30,10.117143,9.798571,8.281429,4.801429,7.892857,5.197143,6.150000,6.377143,6.242857,6.124286,9.720000,8.637143
1961-05-01/1961-05-07,15.367143,13.970000,13.834286,9.952857,14.917143,10.864286,11.435714,12.244286,11.677143,11.585714,17.548571,14.571429
1961-05-08/1961-05-14,7.772857,8.712857,8.172857,5.295714,9.150000,6.391429,8.013333,7.052857,7.528571,7.822857,10.421429,10.382857
1961-05-15/1961-05-21,8.225714,5.631667,12.042857,4.258571,7.597143,5.022857,5.695714,6.970000,6.847143,7.114286,9.624286,10.612857
1961-05-22/1961-05-28,8.155714,7.388571,8.512857,3.748333,6.941429,4.112857,5.142857,6.272857,6.108571,7.535714,10.518571,11.697143
1961-05-29/1961-06-04,10.321429,7.407143,10.065714,6.310000,9.754286,6.451429,8.344286,8.635714,8.714286,9.035714,12.298571,13.597143
1961-06-05/1961-06-11,10.917143,8.992857,8.095714,5.214286,10.030000,5.460000,7.084286,6.884286,8.034286,8.397143,10.148571,12.250000
1961-06-12/1961-06-18,10.571429,9.565714,10.875714,6.520000,10.260000,6.947143,9.278571,9.102857,8.992857,9.594286,15.351429,15.025714
1961-06-19/1961-06-25,7.345714,6.108571,8.084286,5.478571,11.477143,7.492857,11.868571,9.447143,10.458571,11.257143,14.370000,17.410000
1961-06-26/1961-07-02,10.236667,9.482857,8.648571,6.772857,10.975714,6.507143,7.642857,9.237143,7.904286,10.268571,14.535714,12.133333
1961-07-03/1961-07-09,11.715714,7.220000,9.320000,7.544286,12.494286,7.982857,11.888333,9.308571,10.732857,10.547143,12.220000,15.987143
1961-07-10/1961-07-16,16.680000,13.518571,11.171429,9.277143,14.524286,8.412857,10.171429,10.507143,9.530000,10.157143,13.520000,12.524286
1961-07-17/1961-07-23,4.202857,4.255714,6.738571,3.300000,6.112857,2.715714,3.964286,5.642857,5.297143,6.041429,7.524286,8.415714
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-06-05/1978-06-11,12.022857,9.154286,9.488571,5.971429,10.637143,8.030000,8.678571,8.227143,9.172857,9.642857,11.632857,17.778571
1978-06-12/1978-06-18,9.410000,8.770000,14.135714,6.457143,8.564286,6.898571,7.297143,7.464286,7.054286,6.225714,11.398571,12.957143
1978-06-19/1978-06-25,12.707143,10.244286,8.912857,5.878571,10.372857,6.852857,7.648571,7.875714,7.865714,7.084286,13.030000,16.678571
1978-06-26/1978-07-02,12.208571,9.640000,10.482857,7.011429,12.772857,9.005714,11.055714,8.917143,9.994286,7.498571,12.268571,15.287143
1978-07-03/1978-07-09,18.052857,12.630000,11.984286,9.220000,13.414286,10.762857,11.368571,11.218571,11.272857,11.082857,14.754286,18.215714
1978-07-10/1978-07-16,5.882857,3.244286,5.358571,2.250000,4.618571,2.631429,2.494286,3.540000,3.397143,3.214286,7.198571,7.578571
1978-07-17/1978-07-23,13.654286,10.007143,9.915714,6.577143,10.757143,8.282857,8.147143,9.301429,8.952857,8.402857,13.847143,14.785714
1978-07-24/1978-07-30,12.172857,11.854286,11.094286,6.631429,9.918571,8.707143,7.458571,9.117143,9.304286,8.148571,15.192857,14.584286
1978-07-31/1978-08-06,12.475714,9.488571,10.584286,5.457143,8.724286,5.855714,7.065714,5.410000,6.631429,4.962857,9.084286,11.405714
1978-08-07/1978-08-13,10.114286,9.600000,7.635714,4.790000,8.101429,6.702857,5.452857,5.964286,7.518571,5.661429,10.691429,11.927143
1978-08-14/1978-08-20,11.100000,11.237143,10.505714,5.697143,9.910000,8.034286,7.267143,8.517143,9.815714,7.941429,15.000000,14.405714
1978-08-21/1978-08-27,6.208571,5.060000,8.565714,3.121429,4.638571,4.077143,3.291429,3.500000,5.877143,4.447143,8.131429,10.661429
1978-08-28/1978-09-03,8.232857,4.888571,7.767143,3.588571,3.892857,5.090000,6.184286,3.000000,6.202857,4.745714,8.105714,13.150000
1978-09-04/1978-09-10,11.487143,12.742857,11.124286,5.702857,10.721429,10.927143,9.157143,9.458571,10.588571,8.274286,14.560000,16.752857
1978-09-11/1978-09-17,12.067143,10.648571,11.610000,6.864286,12.252857,11.868571,13.017143,12.447143,11.908571,10.957143,18.422857,23.441429
1978-09-18/1978-09-24,5.845714,8.317143,9.305714,2.554286,5.625714,5.171429,7.047143,6.750000,6.870000,6.291429,13.447143,15.324286
1978-09-25/1978-10-01,16.252857,14.131429,12.098571,8.832857,15.810000,10.338571,15.124286,12.378571,12.275714,11.970000,19.160000,24.158571
1978-10-02/1978-10-08,12.865714,13.302857,11.671429,6.531429,11.731429,8.881429,9.707143,9.708571,11.391429,10.161429,16.498571,20.618571
1978-10-09/1978-10-15,9.611429,6.327143,9.250000,4.167143,6.821429,6.237143,5.577143,6.348571,7.232857,7.285714,12.197143,14.177143
1978-10-16/1978-10-22,9.804286,7.817143,7.642857,5.314286,9.124286,6.862857,9.391429,7.428571,7.765714,8.048571,12.708571,17.868571
1978-10-23/1978-10-29,7.504286,7.702857,8.102857,3.204286,7.464286,5.905714,8.727143,6.652857,7.605714,8.120000,14.487143,16.915714
1978-10-30/1978-11-05,13.060000,13.465714,12.137143,6.682857,9.891429,8.314286,9.775714,9.638571,10.185714,10.422857,18.451429,18.721429
1978-11-06/1978-11-12,14.857143,15.237143,12.007143,7.684286,12.460000,9.352857,10.224286,10.554286,11.168571,12.232857,19.307143,22.522857
1978-11-13/1978-11-19,20.590000,18.998571,17.272857,10.417143,14.220000,11.208571,16.081429,12.915714,13.297143,13.242857,20.357143,23.905714
1978-11-20/1978-11-26,16.498571,13.971429,13.544286,6.361429,10.438571,7.404286,12.797143,7.571429,9.998571,8.915714,15.207143,19.491429
1978-11-27/1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-04/1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-11/1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-18/1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-25/1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [55]:
data.resample?

Signature:
data.resample(
    rule,
    how=None,
    axis=0,
    fill_method=None,
    closed=None,
    label=None,
    convention='start',
    kind=None,
    loffset=None,
    limit=None,
    base=0,
    on=None,
    level=None,
)
Docstring:
Resample time-series data.

Convenience method for frequency conversion and resampling of time
series. Object must have a datetime-like index (`DatetimeIndex`,
`PeriodIndex`, or `TimedeltaIndex`), or pass datetime-like values
to the `on` or `level` keyword.

Parameters
----------
rule : str
    The offset string or object representing target conversion.
how : str
    Method for down/re-sampling, default to 'mean' for downsampling.

    .. deprecated:: 0.18.0
       The new syntax is ``.resample(...).mean()``, or
       ``.resample(...).apply(<func>)``
axis : {0 or 'index', 1 or 'columns'}, default 0
    Which axis to use for up- or down-sampling. For `Series` this
    will default to 0, i.e. along the rows. Must be
    `DatetimeIndex`, `TimedeltaIndex` or `PeriodIndex`.
fill_method : str, default None
    Filling method for upsampling.

    .. deprecated:: 0.18.0
       The new syntax is ``.resample(...).<func>()``,
       e.g. ``.resample(...).pad()``
closed : {'right', 'left'}, default None
    Which side of bin interval is closed. The default is 'left'
    for all frequency offsets except for 'M', 'A', 'Q', 'BM',
    'BA', 'BQ', and 'W' which all have a default of 'right'.
label : {'right', 'left'}, default None
    Which bin edge label to label bucket with. The default is 'left'
    for all frequency offsets except for 'M', 'A', 'Q', 'BM',
    'BA', 'BQ', and 'W' which all have a default of 'right'.
convention : {'start', 'end', 's', 'e'}, default 'start'
    For `PeriodIndex` only, controls whether to use the start or
    end of `rule`.
kind : {'timestamp', 'period'}, optional, default None
    Pass 'timestamp' to convert the resulting index to a
    `DateTimeIndex` or 'period' to convert it to a `PeriodIndex`.
    By default the input representation is retained.
loffset : timedelta, default None
    Adjust the resampled time labels.
limit : int, default None
    Maximum size gap when reindexing with `fill_method`.

    .. deprecated:: 0.18.0
base : int, default 0
    For frequencies that evenly subdivide 1 day, the "origin" of the
    aggregated intervals. For example, for '5min' frequency, base could
    range from 0 through 4. Defaults to 0.
on : str, optional
    For a DataFrame, column to use instead of index for resampling.
    Column must be datetime-like.

    .. versionadded:: 0.19.0

level : str or int, optional
    For a MultiIndex, level (name or number) to use for
    resampling. `level` must be datetime-like.

    .. versionadded:: 0.19.0

Returns
-------
Resampler object

See Also
--------
groupby : Group by mapping, function, label, or list of labels.
Series.resample : Resample a Series.
DataFrame.resample: Resample a DataFrame.

Notes
-----
See the `user guide
<http://pandas.pydata.org/pandas-docs/stable/timeseries.html#resampling>`_
for more.

To learn more about the offset strings, please see `this link
<http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases>`__.

Examples
--------

Start by creating a series with 9 one minute timestamps.

>>> index = pd.date_range('1/1/2000', periods=9, freq='T')
>>> series = pd.Series(range(9), index=index)
>>> series
2000-01-01 00:00:00    0
2000-01-01 00:01:00    1
2000-01-01 00:02:00    2
2000-01-01 00:03:00    3
2000-01-01 00:04:00    4
2000-01-01 00:05:00    5
2000-01-01 00:06:00    6
2000-01-01 00:07:00    7
2000-01-01 00:08:00    8
Freq: T, dtype: int64

Downsample the series into 3 minute bins and sum the values
of the timestamps falling into a bin.

>>> series.resample('3T').sum()
2000-01-01 00:00:00     3
2000-01-01 00:03:00    12
2000-01-01 00:06:00    21
Freq: 3T, dtype: int64

Downsample the series into 3 minute bins as above, but label each
bin using the right edge instead of the left. Please note that the
value in the bucket used as the label is not included in the bucket,
which it labels. For example, in the original series the
bucket ``2000-01-01 00:03:00`` contains the value 3, but the summed
value in the resampled bucket with the label ``2000-01-01 00:03:00``
does not include 3 (if it did, the summed value would be 6, not 3).
To include this value close the right side of the bin interval as
illustrated in the example below this one.

>>> series.resample('3T', label='right').sum()
2000-01-01 00:03:00     3
2000-01-01 00:06:00    12
2000-01-01 00:09:00    21
Freq: 3T, dtype: int64

Downsample the series into 3 minute bins as above, but close the right
side of the bin interval.

>>> series.resample('3T', label='right', closed='right').sum()
2000-01-01 00:00:00     0
2000-01-01 00:03:00     6
2000-01-01 00:06:00    15
2000-01-01 00:09:00    15
Freq: 3T, dtype: int64

Upsample the series into 30 second bins.

>>> series.resample('30S').asfreq()[0:5]   # Select first 5 rows
2000-01-01 00:00:00   0.0
2000-01-01 00:00:30   NaN
2000-01-01 00:01:00   1.0
2000-01-01 00:01:30   NaN
2000-01-01 00:02:00   2.0
Freq: 30S, dtype: float64

Upsample the series into 30 second bins and fill the ``NaN``
values using the ``pad`` method.

>>> series.resample('30S').pad()[0:5]
2000-01-01 00:00:00    0
2000-01-01 00:00:30    0
2000-01-01 00:01:00    1
2000-01-01 00:01:30    1
2000-01-01 00:02:00    2
Freq: 30S, dtype: int64

Upsample the series into 30 second bins and fill the
``NaN`` values using the ``bfill`` method.

>>> series.resample('30S').bfill()[0:5]
2000-01-01 00:00:00    0
2000-01-01 00:00:30    1
2000-01-01 00:01:00    1
2000-01-01 00:01:30    2
2000-01-01 00:02:00    2
Freq: 30S, dtype: int64

Pass a custom function via ``apply``

>>> def custom_resampler(array_like):
...     return np.sum(array_like) + 5
...
>>> series.resample('3T').apply(custom_resampler)
2000-01-01 00:00:00     8
2000-01-01 00:03:00    17
2000-01-01 00:06:00    26
Freq: 3T, dtype: int64

For a Series with a PeriodIndex, the keyword `convention` can be
used to control whether to use the start or end of `rule`.

Resample a year by quarter using 'start' `convention`. Values are
assigned to the first quarter of the period.

>>> s = pd.Series([1, 2], index=pd.period_range('2012-01-01',
...                                             freq='A',
...                                             periods=2))
>>> s
2012    1
2013    2
Freq: A-DEC, dtype: int64
>>> s.resample('Q', convention='start').asfreq()
2012Q1    1.0
2012Q2    NaN
2012Q3    NaN
2012Q4    NaN
2013Q1    2.0
2013Q2    NaN
2013Q3    NaN
2013Q4    NaN
Freq: Q-DEC, dtype: float64

Resample quarters by month using 'end' `convention`. Values are
assigned to the last month of the period.

>>> q = pd.Series([1, 2, 3, 4], index=pd.period_range('2018-01-01',
...                                                   freq='Q',
...                                                   periods=4))
>>> q
2018Q1    1
2018Q2    2
2018Q3    3
2018Q4    4
Freq: Q-DEC, dtype: int64
>>> q.resample('M', convention='end').asfreq()
2018-03    1.0
2018-04    NaN
2018-05    NaN
2018-06    2.0
2018-07    NaN
2018-08    NaN
2018-09    3.0
2018-10    NaN
2018-11    NaN
2018-12    4.0
Freq: M, dtype: float64

For DataFrame objects, the keyword `on` can be used to specify the
column instead of the index for resampling.

>>> d = dict({'price': [10, 11, 9, 13, 14, 18, 17, 19],
...           'volume': [50, 60, 40, 100, 50, 100, 40, 50]})
>>> df = pd.DataFrame(d)
>>> df['week_starting'] = pd.date_range('01/01/2018',
...                                     periods=8,
...                                     freq='W')
>>> df
   price  volume week_starting
0     10      50    2018-01-07
1     11      60    2018-01-14
2      9      40    2018-01-21
3     13     100    2018-01-28
4     14      50    2018-02-04
5     18     100    2018-02-11
6     17      40    2018-02-18
7     19      50    2018-02-25
>>> df.resample('M', on='week_starting').mean()
               price  volume
week_starting
2018-01-31     10.75    62.5
2018-02-28     17.00    60.0

For a DataFrame with MultiIndex, the keyword `level` can be used to
specify on which level the resampling needs to take place.

>>> days = pd.date_range('1/1/2000', periods=4, freq='D')
>>> d2 = dict({'price': [10, 11, 9, 13, 14, 18, 17, 19],
...            'volume': [50, 60, 40, 100, 50, 100, 40, 50]})
>>> df2 = pd.DataFrame(d2,
...                    index=pd.MultiIndex.from_product([days,
...                                                     ['morning',
...                                                      'afternoon']]
...                                                     ))
>>> df2
                      price  volume
2000-01-01 morning       10      50
           afternoon     11      60
2000-01-02 morning        9      40
           afternoon     13     100
2000-01-03 morning       14      50
           afternoon     18     100
2000-01-04 morning       17      40
           afternoon     19      50
>>> df2.resample('D', level=0).sum()
            price  volume
2000-01-01     21     110
2000-01-02     22     140
2000-01-03     32     150
2000-01-04     36      90
File:      ~/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py
Type:      method

In [56]:
# resample data to 'W' week and use the functions
weekly = data.resample('W').agg(['min','max','mean','std'])

In [57]:
weekly

              RPT                                VAL                    \
              min    max       mean       std    min    max       mean
Yr_Mo_Dy
1961-01-01  15.04  15.04  15.040000       NaN  14.96  14.96  14.960000
1961-01-08  10.58  18.50  13.541429  2.631321   6.63  16.88  11.486667
1961-01-15   9.04  19.75  12.468571  3.555392   3.54  12.08   8.967143
1961-01-22   4.92  19.83  13.204286  5.337402   3.42  14.37   9.862857
1961-01-29  13.62  25.04  19.880000  4.619061   9.96  23.91  16.141429
1961-02-05  10.58  24.21  16.827143  5.251408   9.46  24.21  15.460000
1961-02-12  16.00  24.54  19.684286  3.587677  11.54  21.42  16.417143
1961-02-19   6.04  22.50  15.130000  5.064609  11.63  20.17  15.091429
1961-02-26   7.79  25.80  15.221429  7.020716   7.08  21.50  13.625714
1961-03-05  10.96  13.33  12.101429  0.997721   8.83  17.00  12.951429
1961-03-12   4.88  14.79   9.376667  3.732263   8.08  16.96  11.578571
1961-03-19   4.92  16.88  11.911429  3.860036   9.46  15.54  13.501429
1961-03-26   6.29  15.00   9.567143  3.613298   2.58  11.63   8.387143
1961-04-02   5.88  18.25  10.757143  5.046922   3.50  16.29   8.852857
1961-04-09   4.50  18.12  11.964286  4.604392   7.04  14.62  10.654286
1961-04-16   4.71  15.50   8.965714  3.937727   4.83  12.25   8.000000
1961-04-23   4.00  21.09  12.621429  5.676655   3.71  15.41  10.438571
1961-04-30   4.08  16.29  10.117143  4.349662   6.50  14.46   9.798571
1961-05-07   9.87  23.00  15.367143  5.025507  10.29  19.79  13.970000
1961-05-14   3.54  12.79   7.772857  3.371022   3.96  15.12   8.712857
1961-05-21   4.88  15.04   8.225714  3.631730   3.58  10.17   5.631667
1961-05-28   4.96  11.79   8.155714  2.739433   3.67  12.50   7.388571
1961-06-04   7.00  15.92  10.321429  3.099701   4.75   9.79   7.407143
1961-06-11   8.29  14.42  10.917143  2.248597   6.83  11.54   8.992857
1961-06-18   6.13  14.33  10.571429  3.009482   4.12  14.54   9.565714
1961-06-25   4.00   9.00   7.345714  1.982035   3.25   9.50   6.108571
1961-07-02   7.21  13.13  10.236667  2.557856   6.34  14.37   9.482857
1961-07-09   7.29  17.50  11.715714  3.664855   3.75  10.75   7.220000
1961-07-16   8.63  22.50  16.680000  5.168710   7.87  19.29  13.518571
1961-07-23   3.04   5.88   4.202857  1.047978   2.92   6.79   4.255714
...           ...    ...        ...       ...    ...    ...        ...
1978-06-11   7.50  21.54  12.022857  4.672682   5.58  12.12   9.154286
1978-06-18   5.17  15.16   9.410000  3.739590   4.63  15.41   8.770000
1978-06-25   8.46  17.58  12.707143  3.687505   7.58  15.25  10.244286
1978-07-02   9.08  16.04  12.208571  2.573820   7.71  14.42   9.640000
1978-07-09   8.54  25.84  18.052857  7.468681   6.92  18.08  12.630000
1978-07-16   3.13  11.21   5.882857  2.640169   2.17   4.29   3.244286
1978-07-23   6.38  19.58  13.654286  4.425931   6.25  17.88  10.007143
1978-07-30   8.00  14.96  12.172857  2.220606   7.87  14.62  11.854286
1978-08-06   5.25  20.58  12.475714  5.520244   5.58  15.09   9.488571
1978-08-13   5.63  13.54  10.114286  3.656418   3.79  13.96   9.600000
1978-08-20   5.41  17.16  11.100000  4.269020   6.04  18.25  11.237143
1978-08-27   3.04  14.92   6.208571  4.538614   1.75  14.42   5.060000
1978-09-03   3.50  13.25   8.232857  4.110400   1.63   7.79   4.888571
1978-09-10   5.83  16.46  11.487143  4.238230   7.33  18.12  12.742857
1978-09-17   5.25  19.38  12.067143  4.531172   3.46  13.92  10.648571
1978-09-24   0.79  11.63   5.845714  3.895197   1.21  13.67   8.317143
1978-10-01   9.50  26.75  16.252857  6.512101   6.83  19.21  14.131429
1978-10-08   8.21  21.67  12.865714  4.502721   7.67  21.00  13.302857
1978-10-15   4.29  15.41   9.611429  4.574004   0.21  11.17   6.327143
1978-10-22   4.46  18.91   9.804286  5.247850   4.17  15.63   7.817143
1978-10-29   2.04  11.54   7.504286  3.156500   1.21  13.46   7.702857
1978-11-05   8.58  18.75  13.060000  3.787180   4.29  19.04  13.465714
1978-11-12   7.38  25.41  14.857143  6.126537   8.12  22.58  15.237143
1978-11-19  13.88  30.21  20.590000  5.487249  11.67  27.63  18.998571
1978-11-26   9.54  23.16  16.498571  4.050216   8.33  17.71  13.971429
1978-12-03   9.08  21.29  14.934286  4.931754   4.54  21.34  11.232857
1978-12-10   9.92  29.33  20.740000  7.215012  12.54  24.79  19.190000
1978-12-17   9.87  23.13  16.758571  4.499431   3.21  24.04  14.692857
1978-12-24   6.21  16.62  11.155714  3.522759   3.63  13.29   8.008571
1978-12-31   7.21  20.33  14.951429  4.350400   5.46  17.41  11.801429

                        ROS         ...        CLO              BEL         \
                 std    min    max  ...       mean       std    min    max
Yr_Mo_Dy                            ...
1961-01-01       NaN  13.17  13.17  ...  12.580000       NaN  18.50  18.50
1961-01-08  3.949525   7.62  12.33  ...   8.497143  1.704941   5.46  17.54
1961-01-15  3.148945   7.08  19.50  ...   7.571429  4.084293   5.25  20.71
1961-01-22  3.837785   7.29  20.79  ...   8.124286  4.783952   6.50  15.92
1961-01-29  5.170224  12.67  25.84  ...  15.640000  3.713368  14.04  27.71
1961-02-05  5.187395   9.04  19.70  ...   9.460000  2.839501   9.17  19.33
1961-02-12  3.608373  13.67  21.34  ...  14.440000  1.746749  15.21  26.38
1961-02-19  3.575012   6.13  19.41  ...  13.542857  2.531361  14.09  29.63
1961-02-26  5.147348   6.08  22.42  ...  12.730000  4.920064   9.59  23.21
1961-03-05  2.851955   8.17  13.67  ...  12.370000  1.593685  11.58  23.45
1961-03-12  3.230167   7.54  16.38  ...  10.458571  3.655113  10.21  22.71
1961-03-19  2.352867   5.25  13.96  ...  11.627143  3.099472  11.29  22.79
1961-03-26  3.657265   4.79  15.63  ...  11.481429  2.538224   8.25  21.34
1961-04-02  4.687315   5.09  14.96  ...   9.631429  3.191115   7.21  18.63
1961-04-09  2.845399   9.29  18.29  ...   7.238571  2.336182   7.62  17.16
1961-04-16  2.607118   3.92  15.79  ...   6.178571  2.161137   5.75  16.17
1961-04-23  4.631736   3.33  17.00  ...   9.551429  3.347972   6.75  19.21
1961-04-30  2.871425   2.54  14.96  ...   6.124286  2.840568   5.13  13.04
1961-05-07  3.750835   8.42  21.21  ...  11.585714  3.620819   4.79  28.08
1961-05-14  3.782947   4.63  12.33  ...   7.822857  5.460237   6.54  18.66
1961-05-21  2.468906   5.91  15.96  ...   7.114286  2.216889   6.63  12.00
1961-05-28  3.378537   3.58  20.96  ...   7.535714  2.575661   6.13  14.33
1961-06-04  1.868125   6.83  15.96  ...   9.035714  2.096989   8.71  17.00
1961-06-11  1.524836   6.04  11.58  ...   8.397143  2.158323   5.37  16.17
1961-06-18  3.509444   6.50  15.50  ...   9.594286  3.792400   7.29  25.25
1961-06-25  2.212460   5.13  10.37  ...  11.257143  2.286218  11.00  19.08
1961-07-02  2.902411   7.62  10.79  ...  10.268571  1.564144   6.96  21.87
1961-07-09  2.686658   7.41  14.92  ...  10.547143  3.657179   7.08  20.41
1961-07-16  3.849630   8.00  14.29  ...  10.157143  3.271899   5.04  20.25
1961-07-23  1.400010   4.08  12.67  ...   6.041429  1.439785   4.21  10.13
...              ...    ...    ...  ...        ...       ...    ...    ...
1978-06-11  2.025396   5.75  13.83  ...   9.642857  2.273549   8.63  14.25
1978-06-18  3.840352   7.21  28.58  ...   6.225714  3.132852   7.75  16.00
1978-06-25  2.821352   6.63  11.17  ...   7.084286  3.451183   7.71  19.29
1978-07-02  2.423111   9.25  12.75  ...   7.498571  1.043926  10.41  14.09
1978-07-09  4.793815   6.25  17.71  ...  11.082857  5.994049  10.08  20.12
1978-07-16  0.897865   3.63   8.00  ...   3.214286  1.497118   4.17  11.63
1978-07-23  3.971094   6.83  17.08  ...   8.402857  3.402086   5.63  24.17
1978-07-30  2.396183   6.58  15.63  ...   8.148571  2.806584   8.38  20.12
1978-08-06  3.574877   6.34  20.17  ...   4.962857  3.902588   5.46  15.75
1978-08-13  3.734577   4.54  11.00  ...   5.661429  2.502895   5.46  16.54
1978-08-20  4.179588   7.71  13.92  ...   7.941429  3.398168   9.29  21.79
1978-08-27  4.838726   4.79  15.00  ...   4.447143  2.569343   6.67   9.29
1978-09-03  2.290542   3.88  10.54  ...   4.745714  1.643541   5.00  11.58
1978-09-10  3.817581   3.42  21.50  ...   8.274286  4.156095   7.17  22.58
1978-09-17  3.357536   6.38  14.09  ...  10.957143  3.011980  11.04  25.33
1978-09-24  5.119608   4.38  13.59  ...   6.291429  4.109499   4.71  19.92
1978-10-01  4.264702   8.25  16.66  ...  11.970000  3.547497  10.63  26.83
1978-10-08  5.521998   6.54  16.25  ...  10.161429  2.903764  10.25  21.29
1978-10-15  4.579559   3.54  12.83  ...   7.285714  4.799798   5.09  18.75
1978-10-22  4.970492   4.83  13.29  ...   8.048571  3.298633   7.87  19.55
1978-10-29  4.152938   5.00  12.21  ...   8.120000  2.796712   7.54  18.38
1978-11-05  4.994834   9.92  16.58  ...  10.422857  3.583940   8.71  23.13
1978-11-12  5.002149   7.29  20.88  ...  12.232857  3.009566  15.16  24.17
1978-11-19  5.686904   8.79  25.46  ...  13.242857  3.369286  16.00  23.79
1978-11-26  3.574854   7.92  18.25  ...   8.915714  4.108965   7.54  21.09
1978-12-03  5.978968   8.21  24.04  ...   9.547143  6.284973   4.92  21.42
1978-12-10  4.953060   7.21  25.37  ...  14.082857  5.516405   9.54  26.08
1978-12-17  7.578665   8.04  18.05  ...   8.565714  5.487801   5.00  21.50
1978-12-24  3.882900   8.50  22.21  ...   8.072857  3.023131   3.21  19.79
1978-12-31  4.705392   7.83  27.29  ...  11.471429  5.533397   1.21  21.79

                                   MAL
                 mean       std    min    max       mean        std
Yr_Mo_Dy
1961-01-01  18.500000       NaN  15.04  15.04  15.040000        NaN
1961-01-08  12.481429  4.349139  10.88  16.46  13.238571   1.773062
1961-01-15  11.125714  5.552215   5.17  16.92  11.024286   4.692355
1961-01-22   9.821429  3.626584   6.79  17.96  11.434286   4.237239
1961-01-29  20.930000  5.210726  17.50  27.63  22.530000   3.874721
1961-02-05  14.012857  4.210858   7.17  19.25  11.935714   4.336104
1961-02-12  21.832857  4.063753  17.04  21.84  19.155714   1.828705
1961-02-19  21.167143  5.910938  10.96  22.58  16.584286   4.685377
1961-02-26  16.304286  5.091162   6.67  23.87  14.322857   6.182283
1961-03-05  17.842857  4.332331   8.83  17.54  13.951667   3.021387
1961-03-12  16.701429  4.358759   5.54  22.54  14.420000   5.769890
1961-03-19  19.350000  3.779727  11.34  22.95  16.227143   4.331958
1961-03-26  14.037143  4.318069  13.13  22.50  18.134286   3.701846
1961-04-02  13.471429  4.179854   7.17  19.58  13.900000   3.924555
1961-04-09  11.712857  3.147781   7.21  15.34  11.371429   2.598271
1961-04-16   9.482857  3.641464   5.66  12.87   8.690000   2.747842
1961-04-23  13.620000  4.735096   4.96  20.46  12.470000   5.908542
1961-04-30   9.720000  2.948237   2.67  17.50   8.637143   5.108365
1961-05-07  17.548571  8.003490   3.83  26.58  14.571429   7.728504
1961-05-14  10.421429  3.968272   3.33  26.30  10.382857   7.858246
1961-05-21   9.624286  1.975853   5.91  14.96  10.612857   3.310819
1961-05-28  10.518571  3.024524   8.00  17.04  11.697143   3.811818
1961-06-04  12.298571  2.611139  10.63  17.96  13.597143   2.593586
1961-06-11  10.148571  3.993062   5.96  19.83  12.250000   4.925055
1961-06-18  15.351429  6.477887   6.13  24.71  15.025714   6.242673
1961-06-25  14.370000  2.498386  13.75  21.50  17.410000   3.063011
1961-07-02  14.535714  6.303747   8.50  16.79  12.133333   3.652313
1961-07-09  12.220000  4.537988  12.08  21.29  15.987143   3.665705
1961-07-16  13.520000  4.971060   5.96  21.96  12.524286   4.974273
1961-07-23   7.524286  2.050218   5.41  10.92   8.415714   2.133994
...               ...       ...    ...    ...        ...        ...
1978-06-11  11.632857  1.855485  16.08  21.17  17.778571   1.868203
1978-06-18  11.398571  3.233592   8.25  19.17  12.957143   3.985234
1978-06-25  13.030000  4.054463  10.25  26.96  16.678571   5.457708
1978-07-02  12.268571  1.633702  13.96  17.00  15.287143   1.100586
1978-07-09  14.754286  4.259209   6.42  28.25  18.215714   7.467112
1978-07-16   7.198571  2.876383   2.13  12.25   7.578571   3.192989
1978-07-23  13.847143  6.197910   8.50  21.96  14.785714   5.235163
1978-07-30  15.192857  4.207928   7.71  20.38  14.584286   5.037681
1978-08-06   9.084286  3.575271   3.92  19.08  11.405714   5.784845
1978-08-13  10.691429  3.698547   5.91  15.79  11.927143   4.068901
1978-08-20  15.000000  4.190449   9.25  27.25  14.405714   6.297801
1978-08-27   8.131429  0.985553   7.41  16.04  10.661429   3.098050
1978-09-03   8.105714  2.295240   6.92  16.88  13.150000   3.534119
1978-09-10  14.560000  6.078306   8.96  25.96  16.752857   5.970128
1978-09-17  18.422857  4.633917  17.58  30.54  23.441429   5.022760
1978-09-24  13.447143  6.213667   5.13  20.00  15.324286   5.514456
1978-10-01  19.160000  4.981663  14.09  33.50  24.158571   6.933240
1978-10-08  16.498571  3.811554  14.04  28.16  20.618571   4.173078
1978-10-15  12.197143  5.412069   4.58  20.04  14.177143   5.653004
1978-10-22  12.708571  4.027573   8.58  28.21  17.868571   6.415230
1978-10-29  14.487143  3.684484  12.62  22.37  16.915714   3.593883
1978-11-05  18.451429  4.908793  10.67  25.00  18.721429   4.229277
1978-11-12  19.307143  3.206518  15.63  29.04  22.522857   5.297445
1978-11-19  20.357143  3.155385  17.88  27.42  23.905714   3.406175
1978-11-26  15.207143  5.597612  11.08  26.67  19.491429   6.677229
1978-12-03  11.835714  5.950112  11.50  25.75  18.728571   6.393188
1978-12-10  18.517143  5.600389  15.34  34.59  23.061429   8.093976
1978-12-17  11.102857  6.631925   6.92  22.83  15.562857   6.005594
1978-12-24  11.845714  5.750301  10.29  31.71  18.977143   7.194108
1978-12-31  12.947143  7.523148  11.96  41.46  26.844286  11.621233

[940 rows x 48 columns]

In [58]:
data.resample('W').agg(['min','max']).head()

              RPT           VAL           ROS          KIL           SHA  \
              min    max    min    max    min    max   min    max    min
Yr_Mo_Dy
1961-01-01  15.04  15.04  14.96  14.96  13.17  13.17  9.29   9.29    NaN
1961-01-08  10.58  18.50   6.63  16.88   7.62  12.33  4.58  10.13   4.54
1961-01-15   9.04  19.75   3.54  12.08   7.08  19.50  0.67  10.54   2.29
1961-01-22   4.92  19.83   3.42  14.37   7.29  20.79  1.04  18.54   3.67
1961-01-29  13.62  25.04   9.96  23.91  12.67  25.84  6.04  17.54  10.00

                   ...    CLA           MUL           CLO           BEL  \
              max  ...    min    max    min    max    min    max    min
Yr_Mo_Dy           ...
1961-01-01    NaN  ...  10.25  10.25  10.83  10.83  12.58  12.58  18.50
1961-01-08  12.62  ...   1.79  10.04   5.83  10.92   5.88  10.46   5.46
1961-01-15  10.37  ...   0.58  11.50   0.50  10.37   2.67  14.58   5.25
1961-01-22  13.96  ...   2.79  11.38   1.92  14.67   2.71  16.71   6.50
1961-01-29  24.08  ...   8.71  20.25   7.12  21.46  11.04  19.95  14.04

                     MAL
              max    min    max
Yr_Mo_Dy
1961-01-01  18.50  15.04  15.04
1961-01-08  17.54  10.88  16.46
1961-01-15  20.71   5.17  16.92
1961-01-22  15.92   6.79  17.96
1961-01-29  27.71  17.50  27.63

[5 rows x 24 columns]

In [59]:
# 1year = 52week

weekly.index[1:53]

DatetimeIndex(['1961-01-08', '1961-01-15', '1961-01-22', '1961-01-29',
               '1961-02-05', '1961-02-12', '1961-02-19', '1961-02-26',
               '1961-03-05', '1961-03-12', '1961-03-19', '1961-03-26',
               '1961-04-02', '1961-04-09', '1961-04-16', '1961-04-23',
               '1961-04-30', '1961-05-07', '1961-05-14', '1961-05-21',
               '1961-05-28', '1961-06-04', '1961-06-11', '1961-06-18',
               '1961-06-25', '1961-07-02', '1961-07-09', '1961-07-16',
               '1961-07-23', '1961-07-30', '1961-08-06', '1961-08-13',
               '1961-08-20', '1961-08-27', '1961-09-03', '1961-09-10',
               '1961-09-17', '1961-09-24', '1961-10-01', '1961-10-08',
               '1961-10-15', '1961-10-22', '1961-10-29', '1961-11-05',
               '1961-11-12', '1961-11-19', '1961-11-26', '1961-12-03',
               '1961-12-10', '1961-12-17', '1961-12-24', '1961-12-31'],
              dtype='datetime64[ns]', name='Yr_Mo_Dy', freq='W-SUN')

In [60]:
weekly.loc[weekly.index[1:53], "RPT":"MAL"].head()

              RPT                               VAL                    \
              min    max       mean       std   min    max       mean
Yr_Mo_Dy
1961-01-08  10.58  18.50  13.541429  2.631321  6.63  16.88  11.486667
1961-01-15   9.04  19.75  12.468571  3.555392  3.54  12.08   8.967143
1961-01-22   4.92  19.83  13.204286  5.337402  3.42  14.37   9.862857
1961-01-29  13.62  25.04  19.880000  4.619061  9.96  23.91  16.141429
1961-02-05  10.58  24.21  16.827143  5.251408  9.46  24.21  15.460000

                        ROS         ...        CLO              BEL         \
                 std    min    max  ...       mean       std    min    max
Yr_Mo_Dy                            ...
1961-01-08  3.949525   7.62  12.33  ...   8.497143  1.704941   5.46  17.54
1961-01-15  3.148945   7.08  19.50  ...   7.571429  4.084293   5.25  20.71
1961-01-22  3.837785   7.29  20.79  ...   8.124286  4.783952   6.50  15.92
1961-01-29  5.170224  12.67  25.84  ...  15.640000  3.713368  14.04  27.71
1961-02-05  5.187395   9.04  19.70  ...   9.460000  2.839501   9.17  19.33

                                   MAL
                 mean       std    min    max       mean       std
Yr_Mo_Dy
1961-01-08  12.481429  4.349139  10.88  16.46  13.238571  1.773062
1961-01-15  11.125714  5.552215   5.17  16.92  11.024286  4.692355
1961-01-22   9.821429  3.626584   6.79  17.96  11.434286  4.237239
1961-01-29  20.930000  5.210726  17.50  27.63  22.530000  3.874721
1961-02-05  14.012857  4.210858   7.17  19.25  11.935714  4.336104

[5 rows x 48 columns]

### pandas - agg 

- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.agg.html

In [61]:
>>> df = pd.DataFrame([[1, 2, 3],
...                    [4, 5, 6],
...                    [7, 8, 9],
...                    [np.nan, np.nan, np.nan]],
...                   columns=['A', 'B', 'C'])

In [62]:
df

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [63]:
df.agg(['min', 'max'])

       A    B    C
min  1.0  2.0  3.0
max  7.0  8.0  9.0

In [64]:
df.agg({'A' : ['sum', 'min'], 'B' : ['min', 'max']})

        A    B
max   NaN  8.0
min   1.0  2.0
sum  12.0  NaN

In [65]:
df.agg({'A' : ['sum', 'min'], 'B' : ['min', 'max','sum']})

        A     B
max   NaN   8.0
min   1.0   2.0
sum  12.0  15.0

In [66]:
df.agg('mean', axis='columns')

0    2.0
1    5.0
2    8.0
3    NaN
dtype: float64